version: 2.1

jobs:
  build:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          name: test
          command: npm test
      - run:
          name: npm-install
          command: npm install
  integration_tests:
    steps:
      - checkout
      - run:
          name: test


workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - integration_tests:
          requires:
            - build
